### ISSUE TITLE
search.ks fails when time:seconds > 2^31

### ISSUE THREAD

**Issue by JonnyOThan** [maneatingape/rsvp#4]
This is a result of this issue: https://github.com/KSP-KOS/KOS/issues/2721

Interestingly, all 3 parameters to `RANGE()` are supposed to be integers, but KOS will round the first two.

I've locally made a tweak that seems to work, but not sure if this is the best fix:

```
    local window_duration is latest_departure - earliest_departure.

    for x_offset in range(0, window_duration, round(search_interval)) {
        local x is earliest_departure + x_offset.
```

**Comment by maneatingape** [comment]
Great insight on the signed 32 bit integer limitation for `range`, that would have taken me a while to find!
You can see the C# `int` type used in the [RangeValue.cs](https://github.com/KSP-KOS/KOS/blob/develop/src/kOS.Safe/Encapsulation/RangeValue.cs) kOS code:

What RSVP is doing is probably a stretch of the intended use of the `range` statement.
It's a straightforward change to use a `from` loop instead.

Fixed in commit b01cf9e23bce88250407cf1a84f87c4e097f8145
