### ISSUE TITLE
Request: polar insertion

### ISSUE THREAD

**Issue by JonnyOThan** [maneatingape/rsvp#7]
I was going to deploy a relay in polar orbit at the destination, and realized that there’s no option for polar insertion. Perhaps as a “final_orbit_orientation” parameter?  You could do polar_north or polar_south if you wanted to get real fancy, but if it just picked arbitrarily I wouldn’t mind.

**Comment by maneatingape** [comment]
`polar` is currently a supported orientation option for `final_orbit_orientation` in `v5` release and below. 

I was planning on removing it in the next release, because it's causing some difficulties with vessel-to-body transfers and the new orbit refinement logic and I wasn't sure if anyone was using it. Hence the docs were updated to remove it.

I'll investigate to see if it can be kept as an supported option.

**Comment by JonnyOThan** [comment]
Hah, I was pretty sure I had seen it in there, but when re-reading the docs it was gone and figured I was imagining it.

**Comment by maneatingape** [comment]
Restored polar option in commit 82ff7683e695932762ee342d6993f34a581240c6.

As an added bonus it now works even better when the destination is a body with a large SOI to orbit ratio (e.g Mun, Ike, Tylo). You no longer get huge delta-v values of several thousand m/s but much more reasonable values instead.
